version: 2

sources:
  - name: adventure_works
    catalog: mesh_dev_db
    schema: adventure_works
    tables:
      - name: sales_salesorderheader
      - name: sales_salesorderdetail
      - name: sales_creditcard